### ISSUE TITLE
Bug: Types are not exported

### ISSUE THREAD

**Issue by leomelzer** [peerigon/scriptlint#11]
When working with the new feature to evaluate arbitrary `package.json` files, I noticed the types do not get exported as I would expect. 

I've compiled a minimal test case here: https://codesandbox.io/s/funny-dijkstra-mvgxn

As you can see by command-clicking into scriptlint (or by inspecting `dist/index.d.ts` after a build) the output file is empty:

```ts
#!/usr/bin/env node
export {};

```

I believe this could be solved by using `export` rather than `module.exports` in the entrypoint:

```diff
diff --git a/src/index.ts b/src/index.ts
index f64e2fa..d271c32 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -2,4 +2,4 @@
 import scriptlint from "./main";
 import {Config} from "./types";

-module.exports = (config: Partial<Config>) => scriptlint(config, "module");
+export default (config: Partial<Config>) => scriptlint(config, "module");
```

Now `dist/index.d.ts` looks like this:

```
#!/usr/bin/env node
import { Config } from "./types";
declare const _default: (config: Partial<Config>) => (import("./types").Message | import("./types").JsonMessage)[];
export default _default;

```

What do you think @moritzjacobs? Thanks for making scriptlint :)

**Comment by moritzjacobs** [comment]
Fixed with https://github.com/peerigon/scriptlint/pull/18
