### ISSUE TITLE
Bug: Validation fails without `scripts` section

### ISSUE THREAD

**Issue by leomelzer** [peerigon/scriptlint#12]
I tried to validate https://unpkg.com/react@16.8.0/package.json

Note the `package.json` does not contain any scripts or even the section at all for that matter.

This currently fails with:

```
➜ ./dist/cli.js --strict dist/react/package.json
𝖘 [error] TypeError: Cannot convert undefined or null to object
```

It seems like the test https://github.com/peerigon/scriptlint/blob/master/tests/userPackageScripts.test.ts#L39-L47 uses a mock which has always some defined `scripts` -- probably we need to setup another mock? 

Currently we use this one: https://github.com/peerigon/scriptlint/blob/master/tests/__mocks__/fs.js#L5-L9

An interesting question is what to return as validation in this case:

1. Either we could say, no scripts => not valid (maybe in strict mode?)
2. Or we return result => `unknown` (what's the exit code? :))
3. Or we return everything OK, there are no scripts so nothing to get wrong 💯 

I'm leaning towards 3 as it gives freedom to maintainers to choose how they do scripts in e.g. monorepo setups. Maybe this could also be a custom rule to opt-in to say "we handle scripts differently"...

What do you think?

**Comment by moritzjacobs** [comment]
Good catch!

> 3. Or we return everything OK, there are no scripts so nothing to get wrong 💯

I would argue that no scripts section === `"scripts:" {}` which is a linting error because of the missing `dev`, `start` and `test` scripts, so we should default to `{}`

**Comment by moritzjacobs** [comment]
Fixed with https://github.com/peerigon/scriptlint/pull/19
