### ISSUE TITLE
mandatory-dev lint goes against standard naming conventions for development scripts

### ISSUE THREAD

**Issue by nickmccurdy** [peerigon/scriptlint#30]
While I have seen `dev` scripts being used in a smaller number of projects, most of the development scripts I've used have actually been using the `start` script. It's also worth mentioning that npm only has an alias for `start` (not `dev`) and that extremely popular boilerplates like `create-react-app` also use `start` scripts for development servers.

Some maintainers may still prefer having a separate `dev` and `start` script for development and production servers in Node apps though, so I'd recommend keeping the rule but not enabling it by default (or in strict mode).

**Comment by moritzjacobs** [comment]
Thank you for your feedback!

I agree with you when we are talking about frontend projects, using CRA or webpack or gulp etc.. But if you use Node.js, for example in an Express application, `npm start` and `npm run dev` are inherently different things. I have many projects where `start` (=> `node app.js`) is only used in production, while my local workflow is `npm run dev` for running the code in nodemon.

My approach with this was to make people be explicit: either alias `dev` => `start` (or vice versa) or turn off the rule explicitly.

**Comment by nickmccurdy** [comment]
I can understand that logic for backend projects, but I think it's better for the defaults to be frontend/backend agnostic rather than assume conventions that are more typical for backends
